/**
 * OKF Markdown System — Object Knowledge Framework Dossiers
 *
 * Saves and indexes lead records as clean, structured Markdown files (.md).
 * Optimised for:
 *  - AI Vector Searching & LLM RAG
 *  - Human inspection and export
 *  - Long-term audit trail and versioning
 */

import fs from "fs/promises";
import path from "path";
import type { OKFRecord } from "./okf-store";

// Directory for persistent OKF Markdown dossiers
const OKF_DIR = path.join(process.cwd(), "data", "okf");

async function ensureDir() {
  try {
    await fs.mkdir(OKF_DIR, { recursive: true });
  } catch {
    // Already exists
  }
}

/**
 * Serializes an OKFRecord into a clean, markdown dossier with frontmatter.
 */
export function serializeOKFToMarkdown(record: OKFRecord): string {
  const frontmatter = [
    "---",
    `id: "${record.id}"`,
    `okfVersion: ${record.okfVersion}`,
    `source: "${record.source}"`,
    `generatedAt: "${record.generatedAt}"`,
    `name: "${record.identity.name.replace(/"/g, '\\"')}"`,
    `phone: "${record.contact.phone || ""}"`,
    `phoneE164: "${record.contact.phoneE164 || ""}"`,
    `phoneScore: ${record.scores.phoneScore}`,
    `phoneConfidence: ${record.contact.phoneConfidence}`,
    `phoneType: "${record.contact.phoneType}"`,
    `email: "${record.contact.email || ""}"`,
    `emailScore: ${record.scores.emailScore}`,
    `industry: "${record.firmographics.industry}"`,
    `location: "${record.firmographics.location}"`,
    `employeeCount: ${record.firmographics.employeeCount ?? "null"}`,
    `totalScore: ${record.scores.total}`,
    `callReadiness: ${record.scores.callReadiness}`,
    `recommendedAction: "${record.ai.recommendedAction}"`,
    `tags: [${record.ai.tags.map((t) => `"${t}"`).join(", ")}]`,
    "---",
  ].join("\n");

  const body = `
# Lead Dossier: ${record.identity.name}

> Generated by MCP Orchestrator on ${new Date(record.generatedAt).toLocaleString()}  
> Source: **${record.source.toUpperCase()}** ${record.sourceUrl ? `(${record.sourceUrl})` : ""}

---

## 1. Verified Contact Intelligence
- **Primary Phone**: \`${record.contact.phone || "Not provided"}\`
- **Normalized E.164**: \`${record.contact.phoneE164 || "N/A"}\`
- **Phone Accuracy Score**: **${record.scores.phoneScore}/100** (Confidence: ${(record.contact.phoneConfidence * 100).toFixed(0)}%)
- **Line Type**: ${record.contact.phoneType.toUpperCase()}
- **Working Email**: \`${record.contact.email || "Not found"}\` (Confidence: ${(record.contact.emailConfidence * 100).toFixed(0)}%)
- **Decision Maker**: ${record.contact.decisionMaker || "Not identified"} ${record.contact.decisionMakerTitle ? `(${record.contact.decisionMakerTitle})` : ""}

---

## 2. Firmographics & Market Profile
- **Company**: ${record.identity.name}
- **Website**: ${record.identity.website ? `[${record.identity.website}](${record.identity.website})` : "N/A"}
- **Industry**: ${record.firmographics.industry}
- **Location**: ${record.firmographics.location} ${record.firmographics.city ? `(${record.firmographics.city}, ${record.firmographics.state})` : ""}
- **Estimated Headcount**: ${record.firmographics.employeeCount ? `${record.firmographics.employeeCount} employees` : (record.firmographics.employeeRange || "Unknown")}
- **Year Founded**: ${record.firmographics.yearFounded || "Unknown"}

---

## 3. ML & AI Intelligence Scoring
| Metric | Score | Max | Notes |
| :--- | :--- | :--- | :--- |
| **Total Lead Score** | **${record.scores.total}** | 100 | Composite ML Rating |
| ICP Fit | ${record.scores.icpFit} | 25 | Market & Industry Alignment |
| Business Quality | ${record.scores.businessQuality} | 15 | Digital footprint & presence |
| Pain Signal | ${record.scores.painSignal} | 25 | Operational friction & call demand |
| Intent | ${record.scores.intent} | 20 | Hiring & expansion signals |
| Recency | ${record.scores.recency} | 10 | Signal freshness |
| Contactability | ${record.scores.contactability} | 5 | Direct reachability |
| **Phone Accuracy** | **${record.scores.phoneScore}** | 100 | E.164 + Area NANP + Direct Line |
| **Call Readiness** | **${record.scores.callReadiness}** | 100 | Gating score for CALL-E |

### AI Reasoning Hypothesis
${record.ai.hypothesis}

### Recommended Next Action
**${record.ai.recommendedAction.toUpperCase()}**

### Key AI Tags
${record.ai.tags.map((t) => `\`#${t}\``).join(" ")}

${record.ai.qualifyingQuestions && record.ai.qualifyingQuestions.length > 0 ? `
### Qualifying Call Questions
${record.ai.qualifyingQuestions.map((q, i) => `${i + 1}. ${q}`).join("\n")}
` : ""}

---

## 4. Evidence Trail & Verified Observations
${record.evidence.length === 0 ? "_No specific external evidence items recorded._" : record.evidence.map((ev) => `- [${ev.type}] **${ev.claim}** (Source: ${ev.source}, Confidence: ${(ev.confidence * 100).toFixed(0)}%)`).join("\n")}

---

## 5. CALL-E Voice Dispatch Status
- **Dispatched**: ${record.calleStatus.dispatched ? "YES" : "NO"}
- **Goal Run ID**: \`${record.calleStatus.goalRunId || "None"}\`
- **Call Status**: ${record.calleStatus.callStatus ? record.calleStatus.callStatus.toUpperCase() : "NOT_CALLED"}
${record.calleStatus.lastCallResult ? `
\`\`\`json
${JSON.stringify(record.calleStatus.lastCallResult, null, 2)}
\`\`\`
` : ""}

---

## 6. CALL-E Call Context & Mid-Conversation Order Schema
${record.callContext ? `
- **Timezone**: \`${record.callContext.timezone}\` (Local Time: ${record.callContext.localTimeFormatted})
- **Calling Hours**: ${record.callContext.isWithinCallingHours ? "🟢 Within Standard Hours" : "🟡 Outside Standard Hours"} — ${record.callContext.callingWindowMessage}
- **Opening Icebreaker**: "${record.callContext.hooks.openingHook}"
- **Readiness Score**: **${record.callContext.scores.callReadiness}/100** | Phone Accuracy: **${record.callContext.scores.phoneAccuracy}/100** | Pain Intensity: **${record.callContext.scores.painIntensity}/100**

### Qualifying Questions:
${record.callContext.hooks.qualifyingQuestions.map((q, i) => `${i + 1}. ${q}`).join("\n")}

### Anticipated Objections & Prep:
${record.callContext.hooks.objectionsToExpect.map((o, i) => `${i + 1}. ${o}`).join("\n")}

### Mid-Conversation Order Schema:
\`\`\`json
${JSON.stringify(record.callContext.orderResultSchema, null, 2)}
\`\`\`
` : "_Call context bundle will be generated upon enrichment._"}
`;

  return `${frontmatter}\n${body.trim()}\n`;
}

/**
 * Writes the OKF markdown file to disk.
 */
export async function saveOKFMarkdown(record: OKFRecord): Promise<string> {
  await ensureDir();
  const safeName = record.identity.name.replace(/[^a-zA-Z0-9_-]/g, "_").toLowerCase();
  const fileName = `${record.id}_${safeName}.md`;
  const filePath = path.join(OKF_DIR, fileName);

  const markdownContent = serializeOKFToMarkdown(record);
  await fs.writeFile(filePath, markdownContent, "utf8");

  return filePath;
}

/**
 * Reads an OKF markdown file by lead ID.
 */
export async function readOKFMarkdown(leadId: string): Promise<string | null> {
  await ensureDir();
  try {
    const files = await fs.readdir(OKF_DIR);
    const targetFile = files.find((f) => f.startsWith(`${leadId}_`));
    if (!targetFile) return null;
    return await fs.readFile(path.join(OKF_DIR, targetFile), "utf8");
  } catch {
    return null;
  }
}

/**
 * Lists all generated OKF markdown dossiers.
 */
export async function listOKFDossiers(): Promise<Array<{ leadId: string; filePath: string; fileName: string }>> {
  await ensureDir();
  try {
    const files = await fs.readdir(OKF_DIR);
    return files
      .filter((f) => f.endsWith(".md"))
      .map((fileName) => {
        const leadId = fileName.split("_")[0];
        return {
          leadId,
          filePath: path.join(OKF_DIR, fileName),
          fileName,
        };
      });
  } catch {
    return [];
  }
}
